### ISSUE TITLE
Does not respect html handed to text attribute.

### ISSUE THREAD

**Issue by ruzz311** [johnotander/ember-linkify#29]
I'd love to be able to include an icon inside the link that ember-linkify creates for me. The problem is that many popular libraries use an ```<i></i>``` tag to denote icons.  If this add-on were a component it could allow the user to specify the ```<a>``` tag's body.

I guess another suggestion would be to allow html in the text argument of the helper.

**Comment by johnotander** [comment]
Thanks for creating this issue! The current behavior is currently by design, as it assumes that user generated text might be passed to it. I'd like to keep this as the default so it can safely handle user generated content.

However, we could add in the ability to set an`unsafe` option which will render html rather than escape it (for contexts where internal text is passed and we don't have to worry about XSS).

Thoughts?

**Comment by ruzz311** [comment]
After using and abusing this helper earlier this afternoon that's what I came to realize about the intended purpose.  Between looking at the source and looking through what @kevva did over at kevva/url-regex I was able to put together something together.  It probably belongs in the serializer/model but that's another story.  I'll be back to use this add-on when I have user-supplied content, tweets or similar!

I'm closing the issue but if someone comes back to +1 later maybe they'll see someone else had the same idea and thought better than to icky a good project up with unsafe html.  Cheers.
